### ISSUE TITLE
Calculator window isn't resizable

### ISSUE THREAD

**Issue by guihm1** [rlxone/Equinox#13]
Hey! I can't resize the calculator window which opened this way by default.

I'm running macOS Monterey 12.1 (21C52) on a Macbook Air M1.

<img width="1440" alt="bug" src="https://user-images.githubusercontent.com/69226067/148459378-499d222d-1b04-494e-99cb-2fc0ecef015a.png">

_btw, your project is amazing, congrats!_

**Comment by rlxone** [comment]
Hey!
I will fix it in a future version. Thank you for the feedback!

**Comment by rlxone** [comment]
Fixed in 2.0. App store build in review.
https://github.com/rlxone/Equinox/releases/tag/v2.0
