### ISSUE TITLE
Equinox not working on MacOS Monterey?

### ISSUE THREAD

**Issue by StefanoBarison** [rlxone/Equinox#14]
Good morning,

I tried (multiple times) to use Equinox to create a simple dynamic wallpaper using the "Time" feature.
It should show a wallpaper from 00 until 12 AM and then another from 12AM to 00, but it's stuck on one of the two.
I was wondering if something has changed in MacOS Monterey such that the dynamical wallpapers don't work anymore (even if it's still recognised as dynamical )

Thank you

**Comment by rlxone** [comment]
Hi!
Please, try this:
1. Create wallpaper with different filename, because it can cache the old version.
2. Reboot your mac.

**Comment by StefanoBarison** [comment]
Thanks for the hints!
Unfortunately, it seems that the problem is still present. 
Do I have to choose "automatic" for both or light and dark?

Thanks again

**Comment by rlxone** [comment]
Well, I took 2 images and choose time wallpaper. Set 00:00:00 for the first and 12:00:00 for the second image.

![Screenshot 2022-01-19 at 00 01 27](https://user-images.githubusercontent.com/8312717/149643898-238203f0-28ca-4890-b6e2-70b838e795c3.png)
![Screenshot 2022-01-19 at 12 02 10](https://user-images.githubusercontent.com/8312717/149643902-7304cade-2eaf-4d84-99d5-06526e6f76b2.png)

As you can see, it works for me. Can you share your wallpaper with me? I'll check the metadata in your images and try it on my own.

**Comment by StefanoBarison** [comment]
Unfortunately, github seems to not support the sharing of an .heic file.
 
 However, I changed a default wallpaper to static and then to dynamic again, then I rebooted the mac and now it works! 
 Even the default wallpaper was not showing correctly, so something happened in the update I think.
 
 Thanks again for all the help.
 
Best regards

**Comment by rlxone** [comment]
@StefanoBarison 
Nice to see you resolved it!
Yeah, these macOS bugs with custom dynamic wallpapers are so annoying. I hope guys from Apple fix it in future updates.
