### ISSUE TITLE
Time - Images at times skipped when set as the Desktop

### ISSUE THREAD

**Issue by Macintosh-Fan** [rlxone/Equinox#21]
I prepared a sequence of several images beforehand, using Time, with the order: 0:00, 0:05, 0:10, ..., 23:55. However, some of the images are then skipped at times; for example, when it is 13:00, the image set to 14:00 will be shown instead and not change for a while.

Images stored in: https://macintoshfan.com/other/ (Note that the link may be invalid in the future)

What I'm not sure about is if it is a bug to do with dynamic desktops in general; however, using Dynaper (closed-source code), it doesn't seem to have this bug for some reason.

**NOTE: I'm in an area with bad internet, so I'll next be able to send the images in a few days.**

**Comment by W1W1-M** [comment]
Related to issue #19

**Comment by Macintosh-Fan** [comment]
No, it is not @W1W1-M. The issue there is about the app configuration itself with setting up the images before processing them. However, this is related to the image output itself. However, I'll make that a little bit more clear.

Another thing I meant to clarify too: this isn't an issue unique to Equinox (except for Dynaper).

**Comment by W1W1-M** [comment]
Thanks for making that clear

**Comment by rlxone** [comment]
hey @Macintosh-Fan 
if you have `Dynaper`, could you please create and share the same wallpaper with me? I'll compare the metadata.

**Comment by Macintosh-Fan** [comment]
@rlxone, for sure. Although, I'll be able to send it at the end of the week since my internet is not great at the moment.

**Comment by Macintosh-Fan** [comment]
I got some luck with the internet connection. The photos are now in https://macintoshfan.com/other/, @rlxone.

**Comment by rlxone** [comment]
hey @Macintosh-Fan, sorry for delay. Had a glance to compare them and found an issue. Will fix it in upcoming version: App store - in few days, Github - today or tomorrow. Thank you for the collaboration.

Equinox vs Dynaper - 0 differences now.
<img width="199" alt="image" src="https://user-images.githubusercontent.com/8312717/203565478-e8ef1c20-289b-42d9-90c3-a214d0d7686c.png">

**Comment by Macintosh-Fan** [comment]
Looking forward!

**Comment by rlxone** [comment]
Fixed in 2.0. App store build in review.
https://github.com/rlxone/Equinox/releases/tag/v2.0
