### ISSUE TITLE
Add button to transfer Solar Calculator values to a selected picture

### ISSUE THREAD

**Issue by larryqiann** [rlxone/Equinox#37]
Hi,

I'm wondering if it would be possible to add a button to automatically transfer the values from the Calculator to the "currently selected image" when creating a Solar wallpaper. Currently, the values must be copied and pasted manually, which can be time consuming with a large number of images. The proposed button would automatically transfer the values in the calculator to the "currently selected" image in the main window.

Thanks!

**Comment by rlxone** [comment]
Hi, nice idea! I'll add to the upcoming version.

**Comment by rlxone** [comment]
https://github.com/rlxone/Equinox/pull/59
Updated the image so it's now more clear that you can drag and drop over an image as well.
