### ISSUE TITLE
Should be "Drag or save your wallpaper **wherever** you want"

### ISSUE THREAD

**Issue by deme3** [rlxone/Equinox#40]
The string refers to this view:
<img width="576" alt="Screenshot 2023-03-07 alle 14 48 11" src="https://user-images.githubusercontent.com/16635005/223441215-71b2b07a-f367-4871-9e9c-ff393189ba8a.png">

and can be found here:
https://github.com/rlxone/Equinox/blob/ca879a839f2703ce111b4f4d78b663479bd224fe/EquinoxAssets/EquinoxAssets/Localization/en.lproj/Localizable.strings#LL77C0-L77C90

**Comment by rlxone** [comment]
Will be fixed in 3.0
https://github.com/rlxone/Equinox/pull/56
