### ISSUE TITLE
Toronto timezone

### ISSUE THREAD

**Issue by QuailRider43** [rlxone/Equinox#43]
Toronto is listed as GMT-4. It should be GMT-5 (I suspect this is a daylight saving time thing - sorry if I'm just being dense about how EST vs EDT works). Thanks for making such a wonderful piece of software.

**Comment by QuailRider43** [comment]
I've narrowed down the problem. At this time of year with DST, Toronto is GMT-4, so Equinox is correct there. However, when I choose the Toronto GMT-4 option, the Equinox sunrise-sunset curve is wrong by an hour.

**Comment by rlxone** [comment]
Hi, thanks, I'll double-check!

**Comment by bpinney** [comment]
Same in New York (-04:00) on this day. It seems to be an hour off. When I manually select a timezone with -05:00 the results match those of other sun calculators.

**Comment by rlxone** [comment]
Will be fixed in 3.0
https://github.com/rlxone/Equinox/pull/61
