### ISSUE TITLE
Investigate macOS Sonoma Landscape wallpapers

### ISSUE THREAD

**Issue by rlxone** [rlxone/Equinox#45]
https://www.apple.com/macos/sonoma-preview/

**Comment by alxmhn** [comment]
The macOS Sonoma wallpapers are located at /Library/Application Support/com.apple.idleassetsd/Customer/

Custom animations are as easy as replacing a video.

**Comment by rlxone** [comment]
Yeah, seems like it's not related to dynamic wallpapers, so skipping it.
