### ISSUE TITLE
[BUG] Crashes when opening HEIC image

### ISSUE THREAD

**Issue by masteryyh** [rlxone/Equinox#47]
**Problem**
This app crashes when I open any HEIC format image downloaded from pap.er (which is a nice wallpaper app on macOS)

**Reproduce steps**
1. Install Equinox from app store;
2. Download a 5K wallpaper from pap.er (technically any wallpaper should be able to reproduce this, as long as it's HEIC image);
3. Select any type in Equinox, and choose the image file just downloaded, and it will just crash.

**Environment**
Macbook Pro 16-inch with M1 pro, 32GB memory
macOS Ventura 13.4.1

**Comment by rlxone** [comment]
Hi, thanks for reporting! Could you share a file example?

**Comment by rlxone** [comment]
I was testing it with some heic files before the latest version release, but not sure the format is fully supported.

**Comment by rlxone** [comment]
Oh, i can download it from the site you mintioned, never mind 😁

**Comment by rlxone** [comment]
Will be fixed in 3.0
https://github.com/rlxone/Equinox/pull/53
