### ISSUE TITLE
Failure: Oops! Something went wrong

### ISSUE THREAD

**Issue by yurisilpess** [rlxone/Equinox#68]
*Same or similar error to #66  + feature request*
### Appearance-based wallpaper bug

- macOS Sonoma 14.5 (23F79)
- App version: Latest release downloaded off of GitHub

------

## Bug screenshot: 
<img width="1042" alt="Screenshot 2024-06-11 at 12 08 26" src="https://github.com/rlxone/Equinox/assets/99032447/bc9ff7f2-6e84-41d4-9e7c-ff73a0a40675">

## Bug Description

I cannot for the life of me get any of the types to work. I'm mainly trying to create an appearance-type dynamic wallpaper. But even changing the file formats (they were .jpg and I renamed them to .png), still nothing. I've tried other file formats, still, nothing. I have yet to know what is causing the error. I checked the file dimensions and size differences, but they're identical on those regards. 

## Feature Request

The most frustrating part of this is that this app really looks stunning and easy to use, I see its potential and how it would be useful to me as I want to use it more often. Albeit, I think it would be really helpful for the error message to be more specific and tell the user what is causing the issue rather than them having to research or guess what problem might be. I'm pretty sure that an average user will delete the app and give up after a few tries. Overall, I would just like for it to work 😭

### Thank you in advance!

**Comment by rlxone** [comment]
Hi @yurisilpess
Hopefully, your issue is related to this and has already been fixed:
https://github.com/rlxone/Equinox/releases/tag/v4.0
If you're interested in the App Store version please wait a couple of days until i pass the app review.

**Comment by yurisilpess** [comment]
The issue is fixed!! Thank you. Keep up the great work! :D
