### ISSUE TITLE
Appearance wallpaper not changing when i toggle dark mode

### ISSUE THREAD

**Issue by Geddard** [rlxone/Equinox#70]
Here im attaching the images I'm using and the resulting Appearance wallpaper, it seems to do what i need but when i Set it as the wallpaper and toggle dark mode it just never changes to the dark one?

Any ideas what i might be missing?
Should the resulting .heic image be moving when i preview it for example?
I see that if i save the image i uploaded here it saves as .gif but it doesn't move at all.

Im on a m1 macbook air with Sonoma

Here's a recording of the process i took to create it:

https://github.com/rlxone/Equinox/assets/3460028/7ce03e4e-b864-4557-add3-8190241b704c

Light
![p5_city_day](https://github.com/rlxone/Equinox/assets/3460028/3b0058e4-c3b9-452e-8af3-60562356ed91)
Dark
![p5_city_night](https://github.com/rlxone/Equinox/assets/3460028/80406566-6a5b-480b-87d4-ddd61cf4f1fa)

Result
![tempImage0Uy3ub](https://github.com/rlxone/Equinox/assets/3460028/d2d52fe4-ec88-49da-ad10-da579b2fde10)

**Comment by Geddard** [comment]
Ok ended up installing Umbra instead, basically the same type of software but it actualyl works :/ sorry to say

**Comment by kyleerhabor** [comment]
@Geddard this issue is already closed, but I've experienced the same issue and found navigating System Settings > Wallpaper and selecting an item from the resize picker (e.g. "Fill Screen") makes the system register the wallpaper for light and dark mode.
